#!/bin/bash
#SBATCH --job-name=packing
#SBATCH --account=hi65
#SBATCH --time=00:30:00
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --qos=shortq

a.out>>output.dat






